A13V1IB3VIYZZH:
  - www.amazon.fr
  - FR
  - EUR
  - ISO-8859-1
A1F83G8C2ARO7P:
  - www.amazon.co.uk
  - GB
  - GBP
  - ISO-8859-1
A1PA6795UKMFR9:
  - www.amazon.de
  - DE
  - EUR
  - ISO-8859-1
A1RKKUPIHCS9HS:
  - www.amazon.es
  - ES
  - EUR
  - ISO-8859-1
A1VC38T7YXB528:
  - www.amazon.co.jp
  - JP
  - JPY
  - SHIFT_JIS
A21TJRUUN4KGV:
  - www.amazon.in
  - IN
  - INR
  - ISO-8859-1
A2EUQ1WTGCTBG2:
  - www.amazon.ca
  - CA
  - CAD
  - ISO-8859-1
APJ6JRA9NG5V4:
  - www.amazon.it
  - IT
  - EUR
  - ISO-8859-1
ATVPDKIKX0DER:
  - www.amazon.com
  - US
  - USD
  - ISO-8859-1
